"""make user name unique

Revision ID: 1208e45e9231
Revises: dc0f600497a1
Create Date: 2026-01-22 10:41:18.224480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import random

# revision identifiers, used by Alembic.
revision: str = '1208e45e9231'
down_revision: Union[str, Sequence[str], None] = 'dc0f600497a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Logic to handle duplicates before applying the constraint
    connection = op.get_bind()
    
    # Get all users with duplicate names
    result = connection.execute(sa.text(
        "SELECT name FROM users GROUP BY name HAVING COUNT(name) > 1"
    ))
    duplicates = [row[0] for row in result]

    for name in duplicates:
        # Find all users sharing this name
        user_result = connection.execute(
            sa.text("SELECT id FROM users WHERE name = :name"),
            {"name": name}
        )
        # Keep the first one, change the others
        user_ids = [row[0] for row in user_result]
        for user_id in user_ids[1:]:
            new_name = f"{name}_{random.randint(1000, 9999)}"
            connection.execute(
                sa.text("UPDATE users SET name = :new_name WHERE id = :id"),
                {"new_name": new_name, "id": user_id}
            )

    # 2. Now apply the unique index
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###
