"""create document metadata table

Revision ID: 9a98ec8f607c
Revises: 0d95f6a53eea
Create Date: 2026-02-05 17:18:07.569317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a98ec8f607c'
down_revision: Union[str, Sequence[str], None] = '0d95f6a53eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('trapped', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_date_raw', sa.String(), nullable=True),
    sa.Column('modification_date_raw', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_metadata_doc_id'), ['doc_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_documents_metadata_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_documents_metadata_doc_id'))

    op.drop_table('documents_metadata')
    # ### end Alembic commands ###
