"""add hashed_password column

Revision ID: aba12ee28383
Revises: 38888ad23d72
Create Date: 2026-01-22 09:54:25.578453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba12ee28383'
down_revision: Union[str, Sequence[str], None] = '38888ad23d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column as nullable first so existing rows don't crash
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=True))

    # 2. Provide a default value for existing users. 
    # In a real app, you might want to use a specific hash that triggers a password reset.
    op.execute("UPDATE users SET hashed_password = 'place_holder_hash_change_me'")

    # 3. Now that no rows are NULL, we can safely set nullable=False
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
