"""add role to users

Revision ID: dc0f600497a1
Revises: aba12ee28383
Create Date: 2026-01-22 10:05:26.818237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0f600497a1'
down_revision: Union[str, Sequence[str], None] = 'aba12ee28383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the ENUM type manually in the database first (specifically for PostgreSQL)
    # If using SQLite, this step is usually skipped or handled automatically.
    user_role_enum = sa.Enum('ADMIN', 'USER', name='userrole')
    
    # 2. Add the column as NULLABLE initially
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', user_role_enum, nullable=True))

    # 3. Seed existing users with the 'USER' role
    # This ensures no row is left with a NULL value
    op.execute("UPDATE users SET role = 'USER'")

    # 4. Now that all rows have a value, set the column to NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
